-- Migration: Fix: Add RLS policies for password_entries table to allow users to access their own data.
-- Executed at: 2025-08-03T12:27:55Z
-- Generated by AI Agent

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."password_entries";
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON "public"."password_entries";
DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."password_entries";
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."password_entries";

-- Create policies
CREATE POLICY "Enable read access for authenticated users" ON "public"."password_entries"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Enable insert for authenticated users" ON "public"."password_entries"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Enable update for authenticated users" ON "public"."password_entries"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Enable delete for authenticated users" ON "public"."password_entries"
AS PERMISSIVE FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

