-- Migration: Create password_entries table and enable RLS
-- Executed at: 2025-08-02T23:41:47Z
-- Generated by AI Agent

-- Create the password_entries table
CREATE TABLE password_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  title text NOT NULL,
  username text NOT NULL,
  password text NOT NULL,
  notes text
);

-- Enable Row Level Security
ALTER TABLE password_entries ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own entries"
ON password_entries FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own entries"
ON password_entries FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own entries"
ON password_entries FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own entries"
ON password_entries FOR DELETE
USING (auth.uid() = user_id);
